### ISSUE TITLE
invalid json from get_workspaces when workspace contains no windows

### ISSUE THREAD

**Issue by jaustinpage** [b12f/wlstreamer#8] opened 2021-01-20 16:25 UTC
when launching wlstreamer with a workspace that has no windows being drawn on it, I get:
`thread 'main' panicked at 'Invalid json from get_workspaces: Error("invalid type: null, expected a string", line: 103, column: 26)', src/main.rs:326:54`

this is confirmed by:
```
swaymsg -r -t get_workspaces
[
  {
    "id": 6,
    "name": "6",
    "rect": {
      "x": 5760,
      "y": 28,
      "width": 3840,
      "height": 2132
    },
# <TRUNCATED>
    "output": "HDMI-A-1",
    "type": "workspace",
    "representation": "H[Google-chrome Alacritty Alacritty]",
    "focused": true,
    "visible": true
  },
  {
    "id": 19,
    "name": "1",
    "rect": {
      "x": 1920,
      "y": 28,
      "width": 3840,
      "height": 2132
    },
    "focus": [
    ],
    "border": "none",
    "current_border_width": 0,
    "layout": "splith",
    "orientation": "horizontal",
    "percent": null,
    "window_rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "deco_rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "geometry": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "window": null,
    "urgent": false,
    "marks": [
    ],
    "fullscreen_mode": 1,
    "nodes": [
    ],
    "floating_nodes": [
    ],
    "sticky": false,
    "num": 1,
    "output": "DP-4",
    "type": "workspace",
    "representation": null,
    "focused": false,
    "visible": true
  },
  {
    "id": 8,
# <TRUNCATED>
    "type": "workspace",
    "representation": "H[<REDACTED>]",
    "focused": false,
    "visible": true
  }
]
```
Here we can see that for one of the workspaces, we have "representation": null. When I open a window on that workspace, I get a non-null representation, and wlstreamer works.

**Comment by jaustinpage** [comment] 2021-01-20 16:31
it is possible that this is a dupe of https://github.com/b12f/wlstreamer/issues/6, however, it is hard to be certain

**Comment by b12f** [comment] 2021-01-20 21:46
Thanks, this is the information I was looking for. Closing as a dupe of #6, but I'll hopefully have the next version with fixes included done by the end of this week.

**Closed as completed by b12f** 2021-01-20 21:46 UTC
